version: 1
cardano:
  dbname: cexplorer
  user: postgres
  password: password
  host: localhost
  port: 5433
pantasia:
  dbname: pantasia
  user: postgres
  password: password
  host: localhost
  port: 5432
time_interval: 2
